config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(Rails.application.secrets.sidekiq_web_username)) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(Rails.application.secrets.sidekiq_web_password))
end if Rails.env.production?

Rails.application.routes.draw do
  root 'donations#index'

  get '/thanks', to: 'donations#thanks'

  resources :projects, only: %i[show index]

  scope :donations do
    resource :subscriptions, only: [:create]
    resource :charges, only: [:create]
  end

  namespace :api do
    resource :stripe_events, only: [:create]
    resource :paypal_notifications, only: [:create]
  end

  mount Sidekiq::Web, at: "/sidekiq"
end

app/controllers/projects_controller.rb
class ProjectsController < DonationsController
  def show
    @name = params[:id]
    @project = Project.find(params[:id].to_sym)
    @should_render_partial = template_exists?(@name, _prefixes, true)
  end

  def index
    @project_totals = Charge.project_totals
  end
end

app/views/projects/_gnar.erb
<h2>Gnar is Not Audio Research</h2>

<p>Noisebridge is host to a working group called gnar. We build modular synthesizers, typically in the DIY Eurorack tradition. We do audio research in Digital Signal Processing. We have a lot of electronic music gear.</p>

<p>We have worked with internationally known hardware builders like <a href="http://moddevices.com/mod-duo">MOD Devices</a>, <a href="https://monome.org/aleph/">Monome</a> and <a href="http://bleeplabs.com/delaydelus-user-guide/">Bleep Labs.</a></p>

<p>We are looking for donations to support building a modular eurorack setup from components. We are also briding the gap between analog and digital through building custom sound cards for embedded computers which can interface with control voltage synthesizers. There is a computer music workstation which runs DSP software and composition environments. It needs a reliable audio interface which doesn't crash.</p>

<h3>Current projects</h3>

<ul>
  <li>Terminal Tedium Eurorack modular</li>
  <li>Computer Music Workstation</li>
  <li>Mod Duo</li>
  <li>MIDI to Monome Serial DIY converter</li>
</ul>

<h3>Expenses</h3>

<ul>
  <li>Cables of all kinds!</li>
  <li>Printed Circuit Boards</li>
  <li>Microcontroller dev boards</li>
  <li>SMD electronics components</li>
  <li>Computer sound cards</li>
  <li>Musical controllers</li>
  <li>Enclosures</li>
  <li>Modular faceplates</li>
</ul>

app/views/projects/_laser.html.erb
<p>Thank you for your supporting our Kaitian <a href="http://www.kaitianlaser.com/2-cutting-engraving-machine-3.html" target="_BLANK">CM1309 Laser Cutter</a>! Noisebridge is proud to make this laser available to absolutely anyone (with training) and hundreds of artists currently use this cutter in their works around the bay.</p>

<p>But there's a catch! Operating and maintaining a 100W industrial laser is not cheap, and we depend on your donations to keep our laser beam bright and shiny. <strong>Please donate a <em>minimum</em> of $5/hour for your laser time.</strong> More is better!</p>

<p>By donating to the laser fund you are directly supporting hundreds of individual creators, and you help keep Noisebridge excellent (and open). As always, your donations to Noisebridge are tax deductible. Thank you!</p>

<div class="embed-responsive embed-responsive-4by3">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/NghQSYxLdng" frameborder="0" allowfullscreen></iframe>
</div>

app/views/projects/_nbsp.html.erb
<h2>&amp;nbsp; - Noisebridge Space Program</h2>

<p>Noisebridge is going to level up in 2018, moving to a new, bigger space! Ideally we'd like to buy a new space, but whether we buy or lease, we need lots of money, both for the moving costs and the real estate itself. So why not help out your friendly local hackerspace! :)</p>

<p>You can read the full call to action for funding <a href="https://noisebridge.net/wiki/FundraisingCall">here</a>.</p>

<p>Notes on the process we're going through in the Noisebridge Space Program are <a href="https://noisebridge.net/wiki/Noisebridge_Space_Program">here</a>.

app/views/projects/_new_lockers.html.erb
<p><b>NEW LOCKERS!!! Yay! More places for more people to stow their projects.</b></p>

<p>We got three banks of used lockers on 6/5/17, adding twenty-three individual lockers to Noisebridge.  TWENTY THREE!!?!!  Twenty three more places for people to stash their projects, worry-free!</p>

<p>The lockers cost $150 to buy and move.  Please help reimburse with your donation!!</p>

<p>Two banks have ten lockers apiece, and they're about the same size as the existing lockers.  The third bank contains three tall lockers, which are perfect for storing your supersuit and a change of street clothes.</p>

<p><a href="https://noisebridge.net/wiki/File:DeSotoCabLockers_20170605_185841-sm.jpg">
  <img src="https://noisebridge.net/images/b/b3/DeSotoCabLockers_20170605_185841-sm.jpg"  width="410" height="540" />
</a></p>

<p><a href="https://noisebridge.net/wiki/File:DeSotoCabLockers_20170605_153355-sm.jpg">
  <img src="https://noisebridge.net/images/a/a4/DeSotoCabLockers_20170605_153355-sm.jpg"  width="510" height="540" />
</a></p>

<p>Until a few years ago these were the personal lockers of taxi drivers at the De Soto Cab Cooperative down in Pacifica. They bear the scars, grafitti, stickers and patina of those times.</p>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 donation-header">
    <%= link_to root_url do %>
      <%= image_tag('noisebridge_logo.jpg', class: 'center noisebridge_logo') %>
    <% end %>
    <h3>Noisebridge: a hackerspace needs your help!</h3>
  </div>

  <div class="col-md-4 col-md-offset-4 donation-form">
    <table class="table">
      <thead>
        <tr>
          <th>Project</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        <% @project_totals.each do |project, amount| %>
          <tr>
            <td><%= link_to project.titleize, project_path(project) %></td>
            <td><%= number_to_currency(amount / 100.0) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 donation-header">
    <%= link_to root_url do %>
      <%= image_tag('noisebridge_logo.jpg', class: 'center noisebridge_logo') %>
    <% end %>
    <h3>Noisebridge: a hackerspace needs your help!</h3>
  </div>
</div>

<% if @project.fundraising_goal? %>
  <div class="col-md-6 col-md-offset-3 donation-progress">
    <%= render partial: "progress_bar", locals: { amount: @project.amount_raised, total: @project.fundraising_goal } %>
  </div>
<% end %>

<div class="row">
  <% if @should_render_partial %>
    <div class="col-md-6 col-md-offset-1 donation-form">
      <%= render partial: @name %>
    </div>

    <div class="col-md-4 donation-form">
      <%= render("project_donation_form", project: true) %>
    </div>
  <% else %>
    <div class="col-md-4 col-md-offset-4 donation-form">
      <%= render("project_donation_form", project: true) %>
    </div>
  <% end %>
</div>